#!/usr/bin/env python3
"""PreToolUse hook: deny Write/Edit to a small set of sensitive paths.

This hook can only ever *narrow* Claude Code's existing manual-approval
flow (emit "deny") -- it must never emit "allow". For every file outside
the denylist below it prints nothing and exits 0, so the normal
manual-approval prompt still fires exactly as it does without this hook.

Denylist rationale (directory rules match at any depth in the path, not just
the top-level component -- some/nested/.ssh/id_rsa is caught exactly like
.ssh/id_rsa):
- .git/                              -- repo internals
- .claude/settings.json,
  .claude/settings.local.json        -- the hook configuration itself
  (matched by exact repo-relative path, not a directory rule)
- hayabusa/                          -- checksum-verified download,
                                         regenerated by download_hayabusa.sh
- lib/                               -- vendored extension deps,
                                         regenerated by package_extension.sh
- .ssh/, .aws/, .gnupg/              -- credential directories, wherever
                                         they appear in the project tree
- .env / .env.<x> (except known
  templates), id_rsa & friends,
  credentials(.json), .npmrc,
  .netrc, and common key/cert
  extensions (.pem/.key/.pfx/.p12/
  .crt/.cer)                         -- credential/secret/key-shaped files,
                                         matched by name/extension anywhere
                                         in the project tree
- anything resolving outside the
  project root                       -- path traversal / absolute-path escape

All comparisons are case-folded so a case-mangled path (e.g. ".GIT/config")
can't slip past the check on a case-insensitive filesystem.

Denial reasons never include a resolved absolute path or any path at all
for the "outside the project root" case -- only repo-relative names/parts
that were already implied by the tool call itself, so nothing about the
local machine (e.g. a username embedded in a home-directory path) leaks
into the message.

Known, accepted gap: this only covers Write/Edit. A Bash command that
mutates one of these paths (rm, mv, shell redirection) is not covered --
Claude Code's own manual approval for Bash still applies regardless, so
this is a defense-in-depth gap, not a regression from today's behavior.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import project_dir, read_hook_input  # noqa: E402

# Repo-internal / vendored directories -- regenerated by this project's own
# tooling, never meant to be hand-edited.
SENSITIVE_DIR_PREFIXES = ("hayabusa", "lib", ".git")

# Credential directories, wherever they appear in the project tree.
CREDENTIAL_DIR_PREFIXES = (".ssh", ".aws", ".gnupg")

# The hook configuration itself, matched by exact repo-relative path.
SENSITIVE_FILES = (".claude/settings.json", ".claude/settings.local.json")

# Credential/secret/key files, matched by exact basename anywhere in the tree.
SENSITIVE_FILE_NAMES = (
    ".env",
    ".npmrc",
    ".netrc",
    "id_rsa",
    "id_ed25519",
    "id_ecdsa",
    "id_dsa",
    "credentials.json",
    "credentials",
)

# .env variants (.env.local, .env.production, ...) are sensitive by default;
# these specific, commonly-committed-on-purpose template names are exempt.
ENV_TEMPLATE_EXEMPTIONS = (".env.example", ".env.sample", ".env.template")

# Common private-key/certificate extensions.
SENSITIVE_EXTENSIONS = (".pem", ".key", ".pfx", ".p12", ".crt", ".cer")

_SENSITIVE_DIR_PREFIXES_LOWER = tuple(p.lower() for p in SENSITIVE_DIR_PREFIXES)
_CREDENTIAL_DIR_PREFIXES_LOWER = tuple(p.lower() for p in CREDENTIAL_DIR_PREFIXES)
_SENSITIVE_FILES_LOWER = {f.lower() for f in SENSITIVE_FILES}
_SENSITIVE_FILE_NAMES_LOWER = {n.lower() for n in SENSITIVE_FILE_NAMES}
_ENV_TEMPLATE_EXEMPTIONS_LOWER = {n.lower() for n in ENV_TEMPLATE_EXEMPTIONS}


def resolve_target(root: Path, file_path: str) -> Path:
    raw = Path(file_path)
    target = raw if raw.is_absolute() else root / raw
    return target.resolve()


def classify(root: Path, file_path: str) -> str | None:
    """Return a human-readable denial reason, or None if the path is fine.

    Reasons never include a resolved absolute path or username -- only
    repo-relative names/parts already implied by the tool call itself.
    """
    resolved = resolve_target(root, file_path)

    try:
        rel = resolved.relative_to(root)
    except ValueError:
        return "path resolves outside the project root"

    rel_str = rel.as_posix()
    if rel_str.lower() in _SENSITIVE_FILES_LOWER:
        return f"{rel_str} is protected hook/settings configuration"

    # Checked at every depth, not just the top-level component -- a sensitive
    # directory nested anywhere in the tree (e.g. some/nested/.ssh/id_rsa) is
    # just as real a target as one directly under the project root.
    for part in rel.parts:
        part_lower = part.lower()
        if part_lower in _SENSITIVE_DIR_PREFIXES_LOWER:
            return f"{part}/ is a protected, regenerated/vendored directory"
        if part_lower in _CREDENTIAL_DIR_PREFIXES_LOWER:
            return f"{part}/ is a protected credential directory"

    name_lower = rel.name.lower()
    if name_lower in _ENV_TEMPLATE_EXEMPTIONS_LOWER:
        return None
    if name_lower in _SENSITIVE_FILE_NAMES_LOWER or name_lower.startswith(".env."):
        return f"{rel.name} looks like a credential/secret/key file"
    if name_lower.endswith(SENSITIVE_EXTENSIONS):
        return f"{rel.name} looks like a credential/secret/key file"

    return None


def main() -> int:
    hook_input = read_hook_input()
    root = project_dir(hook_input)
    file_path = (hook_input.get("tool_input") or {}).get("file_path")

    if not file_path:
        return 0  # no opinion -- normal permission flow applies

    reason = classify(root, file_path)
    if reason is None:
        return 0  # no opinion -- normal permission flow applies

    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": (
                f"Blocked by protect_sensitive_paths hook: {reason}."
            ),
        }
    }))
    return 0


if __name__ == "__main__":
    sys.exit(main())
